server:
  port: 8080
  servlet:
    context-path: /mser/configs
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/imqw/config-application
          username:
          password:
          search-paths: 'cscc,cscc/{application}' #根据输入的{application}自动匹配对应的配置文件--针对有子目录的库
      label: dev          #git配置文件分支
